import streamlit as st
import openai
from docx import Document
import os
# OpenAI API key
openai.api_key = os.getenv("OPENAI_API_KEY")

def generate_response(prompt):
    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[
            {"role": "system", "content": "You are a legal assistant helping to draft a football player contract."},
            {"role": "user", "content": prompt},
        ]
    )
    return response['choices'][0]['message']['content']

def create_contract(data):
    doc = Document()
    doc.add_heading('Football Player Contract', 0)
    
    doc.add_paragraph(f"Player Name: {data['player_name']}")
    doc.add_paragraph(f"Club Name: {data['club_name']}")
    doc.add_paragraph(f"Contract Duration: {data['contract_duration']}")
    doc.add_paragraph(f"Salary: {data['salary']}")
    
    doc.add_heading('Terms and Conditions', level=1)
    doc.add_paragraph(data['terms_conditions'])
    
    doc.add_paragraph("\n\n\n_________________________")
    doc.add_paragraph("Player Signature")
    
    doc.add_paragraph("\n\n\n_________________________")
    doc.add_paragraph("Club Signature")
    
    return doc

# Streamlit interface
st.title("Football Player Contract Generator with AI")

if "step" not in st.session_state:
    st.session_state.step = 0

# Step by step prompts using OpenAI
if st.session_state.step == 0:
    player_name = st.text_input("What is the player's name?")
    if player_name:
        st.session_state.player_name = player_name
        st.session_state.step += 1

if st.session_state.step == 1:
    club_name = st.text_input("What is the club's name?")
    if club_name:
        st.session_state.club_name = club_name
        st.session_state.step += 1

if st.session_state.step == 2:
    contract_duration = st.text_input("What is the duration of the contract?")
    if contract_duration:
        st.session_state.contract_duration = contract_duration
        st.session_state.step += 1

if st.session_state.step == 3:
    salary = st.text_input("What is the player's salary?")
    if salary:
        st.session_state.salary = salary
        st.session_state.step += 1

if st.session_state.step == 4:
    prompt = "Please generate terms and conditions for a football player contract."
    terms_conditions = generate_response(prompt)
    st.text_area("Terms and Conditions (generated by AI)", value=terms_conditions, height=200)
    if st.button("Confirm and Generate Contract"):
        st.session_state.terms_conditions = terms_conditions
        st.session_state.step += 1

if st.session_state.step == 5:
    data = {
        "player_name": st.session_state.player_name,
        "club_name": st.session_state.club_name,
        "contract_duration": st.session_state.contract_duration,
        "salary": st.session_state.salary,
        "terms_conditions": st.session_state.terms_conditions,
    }
    doc = create_contract(data)
    
    doc_name = "football_player_contract.docx"
    doc.save(doc_name)
    
    with open(doc_name, "rb") as file:
        btn = st.download_button(
            label="Download Contract",
            data=file,
            file_name=doc_name,
            mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        )
